=== HectorPascual/scape/xa-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:double"/>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
				<xs:element ref="filters"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deploymentKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deploymentKeys"/>
				<xs:element ref="filterKeys"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Required"/>
				<xs:element ref="Documentation"/>
				<xs:element name="PrefixFromInput" type="xs:string"/>
				<xs:element name="Extension" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation"  minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
                                <xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filter" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
	<xs:element name="Default" type="xs:string"/>
	<xs:element name="Datatype" type="xs:string"/>
	<xs:element name="CliMapping" type="xs:string"/>
</xs:schema>

=== HectorPascual/scape/xa-toolwrapper/examples/oj14.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>openjpeg</id>
    <name>OpenJPEG</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.4</version>
    <services>
        <service sid="1" name="OpenJPEG" type="migrate" servicepackage="eu.scape_project.pc.services">
            <description>Service for converting a Grayscale/RGB TIFF image to JPEG2000 (JP2)</description>
            <operations>
                <operation oid="1" name="convertTiffImageToJp2">
                    <description>Convert a Grayscale/RGB TIFF image to JP2 (Non Grayscale/RGB TIFF not supported!)</description>
                    <command>image_to_j2k_v1_4 -i ${input} -o ${output} -r ${compression} -t ${tileSize} -n ${resolutions} -b ${codeBlockSize} -p ${progressionOrder}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://fue.onb.ac.at/scape/testdata/19080603_0018.tif</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                        <input name="compression">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <Default>20,10,1</Default>
                            <CliMapping>COMPRESSION</CliMapping>
                            <Documentation>Different compression ratios for successive layers - The rate specified for each quality level is the desired compression factor. Example: 20,10,1 means compress 20x, 10x, and lossless.</Documentation>
                        </input>
                        <input name="resolutions">
                            <Datatype>xsd:int</Datatype>
                            <Required>true</Required>
                            <Default>3</Default>
                            <CliMapping>RESOLUTIONS</CliMapping>
                            <Documentation>Number of resolutions</Documentation>
                        </input>
                        <input name="tileSize">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <Default>512,512</Default>
                            <CliMapping>TILESIZE</CliMapping>
                            <Documentation>Size of tile, e.g. 512,512</Documentation>
                        </input>
                        <input name="codeBlockSize">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <Default>32,32</Default>
                            <CliMapping>CODEBLOCKSIZE</CliMapping>
                            <Documentation>Size of code block, e.g. 32,32</Documentation>
                        </input>
                        <input name="progressionOrder">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <Default>LRCP</Default>
                            <CliMapping>PROGRESSIONORDER</CliMapping>
                            <Documentation>Progression order, e.g. LRCP, one of LRCP, RLCP, RPCL, PCRL, CPRL</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>OUTFILE</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>jp2</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deploymentKeys>
                <deploymentKey ref="d1"/>
            </deploymentKeys>
            <filterKeys>
                <filterKey ref="f1"/>
            </filterKeys>
        </service>
    </services>
    <deployments>
        <deployment id="d1">
            <identifier>http://localhost:8080/scape/default/tomcat</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>TxF781!P</password>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
    <filters id="f1">
        <filter>^(https?)://([a-zA-Z\\.]{1,20})([:]?)([0-9]{0,4})([a-zA-Z0-9-_/]{1,200})([\\.]?)([a-z]){0,4}</filter>
    </filters>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/examples/fits50.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>fits</id>
    <name>Fits</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>0.5.0</version>
    <services>
        <service sid="1" name="Fits" type="characterise" servicepackage="eu.scape_project.pc.services">
            <description>FITS (File information toolset Version 0.5.0 including Jhove2)</description>
            <operations>
                <operation oid="1" name="characteriseFile">
                    <description>Characterise a file using FITS</description>
                    <command>/usr/local/fits-0.5.0_J2/fits.sh -i $INFILE -o $OUTFILE</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://fue.onb.ac.at/scape/testdata/19080603_0018.tif</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deploymentKeys>
                <deploymentKey ref="d1"/>
            </deploymentKeys>
            <filterKeys>
                <filterKey ref="f1"/>
            </filterKeys>
        </service>
    </services>
    <deployments>
        <deployment id="d1">
            <identifier>http://localhost:8080/scape/default/tomcat</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>TxF781!P</password>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
    <filters id="f1">
        <filter>^(https?)://([a-zA-Z\\.]{1,20})([:]?)([0-9]{0,4})([a-zA-Z0-9-_/]{1,200})([\\.]?)([a-z]){0,4}</filter>
    </filters>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/examples/tesseract201.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>tesseract</id>
    <name>Tesseract</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>2.0.1</version>
    <installation>
        <os type="linux">
           
        </os>
        <os type="windows">
            
        </os>
    </installation>
    <services>
        <service sid="1" name="Tesseract" type="migrate" servicepackage="eu.scape_project.pc.services">
            <description>Service for copying files</description>
            <operations>
                <operation oid="1" name="ocr">
                    <description>OCR a TIFF image file</description>
                    <command>/usr/bin/tesseract ${input} ${output} -l ${langmod} </command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/scape/testdata/bookpage.tif</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                        <input name="langmod">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <Default>spa</Default>
                            <CliMapping>langmod</CliMapping>
                            <Documentation>Language module to be used by tesseract</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <Extension>txt</Extension>
                            <AutoExtension>true</AutoExtension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		<path>manager</path>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/src/test/resources/examples/oj14.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>openjpeg</id>
    <name>OpenJPEG</name>
    <homepage>http://code.google.com/p/openjpeg/</homepage>
    <version>1.4</version>
    <installation>
        <os type="linux">
            Linux:
            Download: http://openjpeg.googlecode.com/files/openjpeg_v1_4_linux.tgz
            The libtiff and libjpeg must be available on your system.
            OpenJPEG requires at least symbolic links to the libraries at
            /usr/lib/libtiff.so and /usr/lib/libjpeg.so.
            If the libtiff/libjpeg libraries are installed but not available at
            these locations, set symbolic links, e.g.
            sudo ln -s /usr/lib/libjpeg.so.8 /usr/lib/libjpeg.so
            and
            /usr/lib/i386-linux-gnu/libtiff.so.4 /usr/lib/libtiff.so
        </os>
        <os type="windows">
            Windows:
            Download: http://openjpeg.googlecode.com/files/openjpeg_v1_4_win32.zip
        </os>
    </installation>
    <services>
        <service sid="1" name="OpenJPEG" type="migrate" servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>Service for converting a Grayscale/RGB TIFF image to JPEG2000 (JP2)</description>
            <operations>
                <operation oid="1" name="convertTiffImageToJp2">
                    <description>Convert a Grayscale/RGB TIFF image to JP2 (Non Grayscale/RGB TIFF not supported!)</description>
                    <command>/usr/local/openjpeg_v1_4/bin/image_to_j2k -i ${input} -o ${output} -r ${compression} -t ${tileSize} -n ${resolutions} -b ${codeBlockSize} -p ${progressionOrder}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://fue.onb.ac.at/scape/testdata/19080603_0018.tif</Default>
                        </input>
                        <input name="compression">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>compression</CliMapping>
                            <Documentation>Different compression ratios for successive layers - The rate specified for each quality level is the desired compression factor. Example: 20,10,1 means compress 20x, 10x, and lossless.</Documentation>
                            <Default>20,10,1</Default>
                        </input>
                        <input name="resolutions">
                            <Datatype>xsd:int</Datatype>
                            <Required>true</Required>
                            <CliMapping>resolutions</CliMapping>
                            <Documentation>Number of resolutions</Documentation>
                            <Default>3</Default>
                        </input>
                        <input name="tileSize">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>tileSize</CliMapping>
                            <Documentation>Size of tile, e.g. 512,512</Documentation>
                            <Default>512,512</Default>
                        </input>
                        <input name="codeBlockSize">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>codeBlockSize</CliMapping>
                            <Documentation>Size of code block, e.g. 32,32</Documentation>
                            <Default>32,32</Default>
                        </input>
                        <input name="progressionOrder">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>progressionOrder</CliMapping>
                            <Documentation>Progression order, e.g. LRCP, one of LRCP, RLCP, RPCL, PCRL, CPRL</Documentation>
                            <Default>LRCP</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>jp2</Extension>
                        </output>
                    </outputs>
                </operation>
                <operation oid="2" name="simpleConvertTiffImageToJp2">
                    <description>Convert a Grayscale/RGB TIFF image to JP2 (Non Grayscale/RGB TIFF not supported!)</description>
                    <command>/usr/local/openjpeg_v1_4/bin/image_to_j2k -i ${input} -o ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://fue.onb.ac.at/scape/testdata/19080603_0018.tif</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>jp2</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="deployment1"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="deployment1">
            <identifier>http://localhost:8080/scape/default/tomcat</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>TxF781!P</password>
		<path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/pc-as/scape-as-sox-audio2wav.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../scape-core/src/main/resources/eu/scape_project/core/model/toolspec/toolspec.xsd">
    <id>convert</id>
    <name>SoX - Sound eXchange (audio2wav)</name>
    <homepage>http://sox.sourceforge.net/</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            tomcat6,sox
        </os>
        <os type="windows">
            Install sox
        </os>
    </installation>
    <services>
        <service sid="1" name="sox-audio2wav" type="migrate"
            servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>SoX convertion service (audio2wav)</description>
            <operations>
                <operation oid="1" name="convert">
                    <description>Converts any SoX supported audio format to WAV</description>
                    <command>sox ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/audio.flac</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>wav</Extension>
                        </output>
                    </outputs>
                </operation>                
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>

    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/var/lib/tomcat6/webapps/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
