=== HectorPascual/scape/xa-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:double"/>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
				<xs:element ref="filters"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deploymentKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deploymentKeys"/>
				<xs:element ref="filterKeys"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Required"/>
				<xs:element ref="Documentation"/>
				<xs:element name="PrefixFromInput" type="xs:string"/>
				<xs:element name="Extension" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation"  minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
                                <xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filter" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
	<xs:element name="Default" type="xs:string"/>
	<xs:element name="Datatype" type="xs:string"/>
	<xs:element name="CliMapping" type="xs:string"/>
</xs:schema>

=== HectorPascual/scape/xa-toolwrapper/examples/matchboxFindDuplicates.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/main/resources/toolspec.xsd">
    <id>findduplicates</id>
    <name>findduplicates</name>
    <homepage></homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            Available by default.
        </os>
        <os type="windows">
            Use ".bat" instead of ".sh" in the commands defined below.
        </os>
    </installation>
    <services>
        <service sid="1" name="Find Duplicates" type="findduplicates" servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>Service for duplicates detection in collection of digitized documents</description>
            <operations>
                <operation oid="1" name="findDuplicates">
                    <description>Extracts document features</description>
                    <command>FindDuplicates.sh ${inputdir} ${extractiontype} ${outputfile}</command>
                    <inputs>
                        <input name="inputdir">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>inputdir</CliMapping>
                            <Documentation>Input directory that contains documents</Documentation>
                            <Default>/home/user/Samples/CollectionName/</Default>
                        </input>
                        <input name="extractiontype">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>extractiontype</CliMapping>
                            <Documentation>The type of the operation in the process of duplicates finding, one of all, extract, bowhist, compare.</Documentation>
                            <Default>all</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="outputfile">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outputfile</CliMapping>
                            <Documentation>URL reference to output file that contains similarity indexies printed out to standard output</Documentation>
                            <Extension>txt</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>password</password>
				<path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/home/sergiu/Install/apache-tomcat-6.0.35/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/pc-as/scape-as-ffmpeg-audio2mp3.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../scape-core/src/main/resources/eu/scape_project/core/model/toolspec/toolspec.xsd">
    <id>convert</id>
    <name>FFmpeg convert (audio2mp3)</name>
    <homepage>http://ffmpeg.org/</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            tomcat6,ffmpeg
        </os>
        <os type="windows">
            Install ffmpeg
        </os>
    </installation>
    <services>
        <service sid="1" name="ffmpeg-audio2mp3" type="migrate"
            servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>FFmpeg convertion service (audio2mp3)</description>
            <operations>
                <operation oid="1" name="convert">
                    <description>Converts any FFmpeg supported audio format to MP3</description>
                    <command>ffmpeg -y -i ${input} -ab 320k ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/audio/nin-ghosts_I-2.mp3</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>mp3</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/var/lib/tomcat6/webapps/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/examples/droid601.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>droid</id>
    <name>DROID</name>
    <homepage>http://sourceforge.net/apps/mediawiki/droid/</homepage>
    <version>6.0.1</version>
    <installation>
        <os type="linux">
            Install DROID in any directory.
            Edit the examples/droid601-wrapper.sh script to match the DROID installation.
            Edit this file, especailly the 
                services/service/operations/operation/command
            and the 
                deployments/deployment/dataexchange/accessdir
            parameters.
        </os>
    </installation>
    <services>
        <service sid="1" name="Droid" type="characterise" servicepackage="eu.scape_project.pc.services">
            <description>Service for running a DROID characterisation one one file</description>
            <operations>
                <operation oid="1" name="droid">
                    <description>Runs DROID on a single file</description>
                    <command>/usr/local/java/droid/droid601/droid601-wrapper.sh ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/scape/testdata/scape-logo.png</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>csv</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		<path>manager</path>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/src/test/resources/examples/winDROID601.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>copy</id>
    <name>Copy</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>6.0.1</version>
    <installation>
        <os type="linux">
            NOT available.
        </os>
        <os type="windows">
            Use cmd.exe /c winDROID601.cmd INPUT OUTPUT
            
            After installing the DROID tool, makes sure to adapt the files
                examples\winDROID601.xml
                examples\winDROID601.cmd
            appropriately.
            Also keep in mind to adapt the "deployments" section to your tomcat installation.
        </os>
    </installation>
    <services>
        <service sid="1" name="WIN DROID" type="migrate" servicepackage="eu.scape_project.pc.services" contextpathprefix="/wscapeservices">
            <description>Service for copying files</description>
            <operations>
                <operation oid="1" name="winDroid">
                    <description>Copies a file</description>
                    <command>CMD.exe /C C:/_RAMother/DEV_GIT/SCAPE_RW/xa-toolwrapper/examples/winDROID601.cmd ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/scape-logo.png</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>csv</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="localWIN"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		<path>manager/text</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
        <deployment id="localWIN">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		<path>manager/text</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>C:/Programme/ApacheTomcat7.0.14/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/pc-as/scape-as-imagemagick-image2jp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../scape-core/src/main/resources/eu/scape_project/core/model/toolspec/toolspec.xsd">
    <id>convert</id>
    <name>ImageMagick's convert (image2jp2)</name>
    <homepage>http://www.imagemagick.org/script/convert.php</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            tomcat6,imagemagick
        </os>
        <os type="windows">
            Install ImageMagick
        </os>
    </installation>
    <services>
        <service sid="1" name="imagemagick-image2jp2" type="migrate"
            servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>ImageMagick convertion service (image2jp2)</description>
            <operations>
                <operation oid="1" name="convert">
                    <description>Converts any ImageMagick supported image format to JPEG2000</description>
                    <command>/usr/bin/convert ${input}[0] ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/elephant.tiff</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>jp2</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>

    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/var/lib/tomcat6/webapps/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/examples/tika10_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>tika</id>
    <name>Tika</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            NOT available.
        </os>
        <os type="windows">
            Use cmd.exe /c tika10_1.cmd INPUT OUTPUT

            After installing the Tika tool, makes sure to adapt the files
            examples\tika10_1.xml
            examples\tika10_1.cmd
            appropriately.
            Also keep in mind to adapt the "deployments" section to your tomcat installation.
        </os>
    </installation>
    <services>
        <service sid="1" name="Apache Tika" type="migrate" servicepackage="eu.scape_project.pc.services" contextpathprefix="/wscapeservices">
            <description>Service for analyzing files</description>
            <operations>
                <operation oid="1" name="tika">
                    <description>Analyzes a file using the Apache Tika tool</description>
                    <command>CMD.exe /C C:/_RAMother/DEV_GIT/SCAPE_RW/xa-toolwrapper/examples/tika10_1.cmd ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/scape-logo.png</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="localWIN"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager/text</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
        <deployment id="localWIN">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager/text</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>C:/Programme/ApacheTomcat7.0.14/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
