=== HectorPascual/scape/xa-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:double"/>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
				<xs:element ref="filters"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deploymentKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deploymentKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKey">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterKeys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterKey" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deploymentKeys"/>
				<xs:element ref="filterKeys"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Required"/>
				<xs:element ref="Documentation"/>
				<xs:element name="PrefixFromInput" type="xs:string"/>
				<xs:element name="Extension" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation"  minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
                                <xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filter" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
	<xs:element name="Default" type="xs:string"/>
	<xs:element name="Datatype" type="xs:string"/>
	<xs:element name="CliMapping" type="xs:string"/>
</xs:schema>

=== HectorPascual/scape/xa-toolwrapper/examples/copy10.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>copy</id>
    <name>Copy</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.0</version>
    <services>
        <service sid="1" name="Simple Copy" type="migrate" servicepackage="eu.scape_project.pc.services">
            <description>Service for copying files</description>
            <operations>
                <operation oid="1" name="simpleCopy">
                    <description>Copies a file</description>
                    <command>/bin/cp ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/scape/testdata/scape-logo.png</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deploymentKeys>
                <deploymentKey ref="d1"/>
                <deploymentKey ref="d2"/>
            </deploymentKeys>
            <filterKeys>
                <filterKey ref="f1"/>
            </filterKeys>
        </service>
    </services>
    <deployments>
        <deployment id="d1">
            <identifier>http://localhost:8080/scape/default/tomcat</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>TxF781!P</password>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
        <deployment id="d2">
            <identifier>http://fue.onb.ac.at/scape/default/tomcat</identifier>
            <host>fue.onb.ac.at</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>TxF781!P</password>
            </manager>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
    <filters id="f1">
        <filter>^(https?)://([a-zA-Z\\.]{1,20})([:]?)([0-9]{0,4})([a-zA-Z0-9-_/]{1,200})([\\.]?)([a-z]){0,4}</filter>
    </filters>
</toolspec>

=== HectorPascual/scape/pc-qa-toolwrapper/extractFeaturesAndCompare_Version_1.0/extractfeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/main/resources/toolspec.xsd">
    <id>copy</id>
    <name>Copy</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            Available by default.
        </os>
        <os type="windows">
            Use "CMD.exe /C COPY" instead of "/bin/cp" in the commands defined below.
        </os>
    </installation>
    <services>
        <service sid="1" name="Extract features" type="migrate" servicepackage="eu.scape_project.pc.services">
            <description>Service for feature extraction from image files</description>
            <operations>
                <operation oid="1" name="extractFeatures">
                    <description>Extracts image file features</description>
                    <command>extractfeatures.bat ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/testbild1.jpg</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Default>http://localhost:8080/testbild1.xml</Default>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>
                <operation oid="2" name="compare">
                    <description>Compares image file features</description>
                    <command>compare.bat ${input1} ${input2} ${output}</command>
                    <inputs>
                        <input name="input1">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/testbild1.xml</Default>
                            <CliMapping>input1</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                        <input name="input2">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/testbild1c.xml</Default>
                            <CliMapping>input2</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input1</PrefixFromInput>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>				
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		        <path>manager</path>
            </manager>
            <dataexchange>
                <accessdir>../webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/pc-as/mencoder.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xa-toolwrapper/src/main/resources/toolspec.xsd">
    <id>convert</id>
    <name>Mencoder's convert</name>
    <homepage>http://www.mplayerhq.hu/</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            Install Mencoder
        </os>
        <os type="windows">
            Install Mencoder
        </os>
    </installation>
    <services>
        <service sid="1" name="Mencoder" type="migrate"
            servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>Mencoder convertion service</description>
            <operations>
                
                <operation oid="1" name="video2mpeg2">
                    <description>Converts any Mencoder supported video format to MPEG2</description>
                    <command>mencoder -quiet -of mpeg -ovc lavc -oac lavc -lavcopts vcodec=mpeg2video:acodec=ac3 ${input} -o ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://localhost:8080/scape/testdata/video/big_buck_bunny_480p_stereo.ogg.flv</Default>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>mpeg</Extension>
                        </output>
                    </outputs>
                </operation>
                
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>

    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <dataexchange>
                <!--<accessdir>../webapps/ROOT/scape/tmp/</accessdir>-->
                <accessdir>webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/pc-as/scape-as-imagemagick-txt2jp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" model="0.1" xsi:noNamespaceSchemaLocation="../scape-core/src/main/resources/eu/scape_project/core/model/toolspec/toolspec.xsd">
  <id>convert</id>
  <name>ImageMagick's convert (txt2jp2)</name>
  <homepage>http://www.imagemagick.org/script/convert.php</homepage>
  <version>1.0</version>
  <installation>
    <os type="linux">
            tomcat6,imagemagick
        </os>
    <os type="windows">
            Install ImageMagick
        </os>
  </installation>
  <services>
    <service sid="1" name="imagemagick-txt2jp2" type="migrate" servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
      <description>ImageMagick convertion service (txt2jp2)</description>
      <operations>
        <operation oid="1" name="convert">
          <description>Converts Text to JPEG2000</description>
          <command>/usr/bin/convert ${input} ${output}</command>
          <inputs>
            <input name="input">
              <Datatype>xsd:anyURI</Datatype>
              <Required>true</Required>
              <CliMapping>input</CliMapping>
              <Documentation>URL reference to input file</Documentation>
              <Default>http://localhost:8080/scape/testdata/free-text.txt</Default>
            </input>
          </inputs>
          <outputs>
            <output name="output">
              <Datatype>xsd:anyURI</Datatype>
              <Required>false</Required>
              <CliMapping>output</CliMapping>
              <Documentation>URL reference to output file</Documentation>
              <PrefixFromInput>input</PrefixFromInput>
              <Extension>jp2</Extension>
            </output>
          </outputs>
        </operation>
      </operations>
      <deployto>
        <deployref default="true" ref="local"/>
      </deployto>
    </service>
  </services>
  <deployments>
    <deployment id="local">
      <identifier>http://localhost:8080</identifier>
      <host>localhost</host>
      <ports>
        <port type="http">8080</port>
        <port type="https">8043</port>
      </ports>
      <manager>
        <user>tomcat</user>
        <password>tomcat</password>
        <path>manager</path>
      </manager>
      <toolsbasedir/>
      <dataexchange>
        <accessdir>/var/lib/tomcat6/webapps/scape/tmp/</accessdir>
        <accessurl>http://localhost:8080/scape/tmp/</accessurl>
      </dataexchange>
    </deployment>
  </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/examples/file10.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>file</id>
    <name>File</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            Available by default.
        </os>
        <os type="windows">
            Use "CMD.exe /C COPY" instead of "/bin/cp" in the commands defined below.
        </os>
    </installation>
    <services>
        <service sid="1" name="File" type="migrate" servicepackage="eu.scape_project.pc.services" contextpathprefix="/scapeservices">
            <description>Service for copying files</description>
            <operations>
                <operation oid="1" name="identify">
                    <description>Identification of a file</description>
                    <command>file ${input}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/scape/testdata/scape-logo.png</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:string</Datatype>
                            <Required>false</Required>
                            <CliMapping>STDOUT</CliMapping>
                            <Documentation>Output of the tool file</Documentation>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/default/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		<path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>/usr/local/java/apache-tomcat-6.0.29/webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== HectorPascual/scape/xa-toolwrapper/src/test/resources/examples/migrationQA.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="c:\owndata\scape\toolspec.xsd">
    <id>migrationQA</id>
    <name>migrationQA</name>
    <homepage>TODO</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            TODO
        </os>
        <os type="windows">
            TODO
        </os>
    </installation>
    <services>
        <service sid="1" name="migrationQA" type="compare" servicepackage="eu.scape_project.pc.services">
            <description>Service for comparing audio files</description>
            <operations>
                <operation oid="1" name="migrationQA">
                    <description>Compares two wav files</description>
                    <command>migrationQA.sh ${file1} ${file2} ${output}</command>
                    <inputs>
                        <input name="file1">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <Default>http://iapetus:9441/scape-data/test-data/sample1.wav</Default>
                            <CliMapping>file1</CliMapping>
                            <Documentation>URL reference to wav input file 1</Documentation>
                        </input>
                      <input name="file2">
                          <Datatype>xsd:anyURI</Datatype>
                          <Required>true</Required>
                          <Default>http://iapetus:9441/scape-data/test-data/sample2.wav</Default>
                          <CliMapping>file2</CliMapping>
                          <Documentation>URL reference to wav input file 2</Documentation>
                      </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <CliMapping>output</CliMapping>
                            <Required>false</Required>
                            <Documentation>URL reference to output from system.out</Documentation>
                            <PrefixFromInput>file1</PrefixFromInput>
                            <Extension>txt</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="iapetus"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/scape/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>password</password>
                <path>manager</path>
            </manager>
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>webapps/ROOT/scape/tmp/</accessdir>
                <accessurl>http://localhost:8080/scape/tmp/</accessurl>
            </dataexchange>
        </deployment>
        <deployment id="iapetus">
            <identifier>http://iapetus:9441/</identifier>
            <host>iapetus</host>
            <ports>
                <port type="http">9441</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>password</password>
                <path>manager</path>
            </manager>
            <toolsbasedir>/home/scape/tools/migrationQA/</toolsbasedir>
            <dataexchange>
                <accessdir>services/webapps/scape-data/migrationQA-output/</accessdir>
                <accessurl>http://iapetus:9441/scape-data/migrationQA-output/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
